[
  {
    "id": "med001",
    "name": "Acetaminophen 500mg",
    "category": "Pain Relief",
    "price": 12.99,
    "description": "Effective pain reliever and fever reducer for adults and children",
    "symptoms": ["headache", "fever", "pain", "muscle aches"],
    "in_stock": true,
    "stock_count": 50,
    "image": "https://via.placeholder.com/300x200/007bff/ffffff?text=Acetaminophen",
    "dosage": "Take 1-2 tablets every 4-6 hours as needed",
    "warnings": "Do not exceed 8 tablets in 24 hours"
  },
  {
    "id": "med002",
    "name": "Ibuprofen 200mg",
    "category": "Pain Relief",
    "price": 15.49,
    "description": "Anti-inflammatory pain reliever for various conditions",
    "symptoms": ["inflammation", "pain", "fever", "arthritis"],
    "in_stock": true,
    "stock_count": 35,
    "image": "https://via.placeholder.com/300x200/28a745/ffffff?text=Ibuprofen",
    "dosage": "Take 1-2 tablets every 6-8 hours with food",
    "warnings": "May cause stomach irritation"
  },
  {
    "id": "med003",
    "name": "Diphenhydramine 25mg",
    "category": "Allergy",
    "price": 9.99,
    "description": "Antihistamine for allergies and sleep aid",
    "symptoms": ["allergies", "runny nose", "sneezing", "insomnia"],
    "in_stock": true,
    "stock_count": 42,
    "image": "https://via.placeholder.com/300x200/ffc107/000000?text=Diphenhydramine",
    "dosage": "Take 1-2 tablets every 4-6 hours as needed",
    "warnings": "May cause drowsiness"
  },
  {
    "id": "med004",
    "name": "Loratadine 10mg",
    "category": "Allergy",
    "price": 18.75,
    "description": "Non-drowsy antihistamine for seasonal allergies",
    "symptoms": ["seasonal allergies", "hay fever", "sneezing", "watery eyes"],
    "in_stock": true,
    "stock_count": 28,
    "image": "https://via.placeholder.com/300x200/17a2b8/ffffff?text=Loratadine",
    "dosage": "Take 1 tablet once daily",
    "warnings": "Consult doctor if symptoms persist"
  },
  {
    "id": "med005",
    "name": "Dextromethorphan Cough Syrup",
    "category": "Cough & Cold",
    "price": 11.25,
    "description": "Effective cough suppressant for dry coughs",
    "symptoms": ["dry cough", "persistent cough", "throat irritation"],
    "in_stock": true,
    "stock_count": 33,
    "image": "https://via.placeholder.com/300x200/6f42c1/ffffff?text=Cough+Syrup",
    "dosage": "Take 15ml every 4 hours as needed",
    "warnings": "Do not exceed 6 doses in 24 hours"
  },
  {
    "id": "med006",
    "name": "Guaifenesin Expectorant",
    "category": "Cough & Cold",
    "price": 13.50,
    "description": "Helps loosen mucus and clear chest congestion",
    "symptoms": ["chest congestion", "mucus", "productive cough"],
    "in_stock": true,
    "stock_count": 25,
    "image": "https://via.placeholder.com/300x200/20c997/ffffff?text=Expectorant",
    "dosage": "Take 200-400mg every 4 hours",
    "warnings": "Drink plenty of fluids while taking"
  },
  {
    "id": "med007",
    "name": "Omeprazole 20mg",
    "category": "Digestive Health",
    "price": 24.99,
    "description": "Proton pump inhibitor for acid reflux and heartburn",
    "symptoms": ["heartburn", "acid reflux", "stomach acid", "GERD"],
    "in_stock": true,
    "stock_count": 40,
    "image": "https://via.placeholder.com/300x200/dc3545/ffffff?text=Omeprazole",
    "dosage": "Take 1 capsule daily before breakfast",
    "warnings": "May take 1-4 days for full effect"
  },
  {
    "id": "med008",
    "name": "Simethicone Gas Relief",
    "category": "Digestive Health",
    "price": 8.99,
    "description": "Fast relief from gas, bloating, and discomfort",
    "symptoms": ["gas", "bloating", "stomach discomfort", "flatulence"],
    "in_stock": true,
    "stock_count": 55,
    "image": "https://via.placeholder.com/300x200/fd7e14/ffffff?text=Gas+Relief",
    "dosage": "Take 2-4 tablets after meals and at bedtime",
    "warnings": "Safe for daily use"
  }
]
